### ISSUE TITLE
local spork-config.yml does not overwrite user config

### ISSUE THREAD

**Issue by ehaselwanter** [jonlives/knife-spork#110]
having

```
 cat /Users/ehaselwanter/.chef/spork-config.yml
plugins:
  git:
    enabled: true
```

and

```
cat config/spork-config.yml
plugins:
  git:
    enabled: false
```

gives me

```
$ knife spork info |grep Git
KnifeSpork::Plugins::Git: enabled
```

Is this as it should be?
